import { GoogleGenAI } from "@google/genai";

export const getGeminiModel = () => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not set in the environment.");
  }
  const ai = new GoogleGenAI({ apiKey });
  return ai;
};

export const transformRoom = async (imageBase64: string, style: string) => {
  const ai = getGeminiModel();
  
  // Remove the data:image/jpeg;base64, prefix if present
  const base64Data = imageBase64.split(',')[1] || imageBase64;
  
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Data,
            mimeType: 'image/jpeg',
          },
        },
        {
          text: `Redesign this room in ${style} style. 
          Keep the structural layout, walls, windows, and doors exactly as they are. 
          Change the furniture, decor, color palette, and lighting to match the ${style} aesthetic. 
          The output should be a high-quality, photorealistic image of the redesigned room. 
          Ensure the perspective and scale of the original room are maintained.`,
        },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image was generated by the model.");
};
